// <auto-generated />
using System;
using Jobify.Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobify.Domain.Migrations
{
    [DbContext(typeof(JobifyContext))]
    [Migration("20240722233151_AddIndustryTable")]
    partial class AddIndustryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jobify.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Jobify.Domain.Entities.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "business",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Business Development"
                        },
                        new
                        {
                            Id = 2,
                            Code = "copywriting",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Copywriting &amp; Content"
                        },
                        new
                        {
                            Id = 3,
                            Code = "supporting",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Customer Success"
                        },
                        new
                        {
                            Id = 4,
                            Code = "technical-support",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Technical Support"
                        },
                        new
                        {
                            Id = 5,
                            Code = "data-science",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 6,
                            Code = "design-multimedia",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Design &amp; Creative"
                        },
                        new
                        {
                            Id = 7,
                            Code = "web-app-design",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Web &amp; App Design"
                        },
                        new
                        {
                            Id = 8,
                            Code = "admin",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "DevOps &amp; SysAdmin"
                        },
                        new
                        {
                            Id = 9,
                            Code = "engineering",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6820),
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 10,
                            Code = "accounting-finance",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "Finance &amp; Legal"
                        },
                        new
                        {
                            Id = 11,
                            Code = "hr",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "HR &amp; Recruiting"
                        },
                        new
                        {
                            Id = 12,
                            Code = "marketing",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 13,
                            Code = "seller",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 14,
                            Code = "seo",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "SEO"
                        },
                        new
                        {
                            Id = 15,
                            Code = "smm",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = 16,
                            Code = "management",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "Product &amp; Operations"
                        },
                        new
                        {
                            Id = 17,
                            Code = "dev",
                            CreatedAt = new DateTime(2024, 7, 22, 23, 31, 51, 350, DateTimeKind.Utc).AddTicks(6830),
                            Name = "Programming"
                        });
                });

            modelBuilder.Entity("Jobify.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AnnualSalaryMax")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("AnnualSalaryMin")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Geo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IndustryId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Jobify.Domain.Entities.Job", b =>
                {
                    b.HasOne("Jobify.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jobify.Domain.Entities.Industry", "Industry")
                        .WithMany("Jobs")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Jobify.Domain.Entities.Industry", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
